"""Constants for the HomeFleet integration."""

DOMAIN = "homefleet"
CONF_URL = "url"
CONF_INTEGRATION_KEY = "integration_key"
CONF_ENTITIES = "entities"
CONF_INTERVAL = "interval"
DEFAULT_INTERVAL = 5
MAX_INTERVAL = 1440
MAX_REPORT_BYTES = 1_048_576
SOURCE_TIMEOUT_SECONDS = 10
COLLECTION_TIMEOUT_SECONDS = 20
REPORT_TIMEOUT_SECONDS = 55
